CREATE TABLE charge (
  chargeId INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   timestamp TIMESTAMP with time zone,
   chargeAmount DOUBLE PRECISION NOT NULL,
   transactionId INTEGER,
   CONSTRAINT pk_charge PRIMARY KEY (chargeId)
);

CREATE TABLE charging_station (
  chargingStationId INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   identifier VARCHAR(255),
   address VARCHAR(255),
   number INTEGER NOT NULL,
   status INTEGER,
   CONSTRAINT pk_charging_station PRIMARY KEY (chargingStationId)
);

CREATE TABLE company_price (
  companyPriceId INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   startFee DOUBLE PRECISION NOT NULL,
   perKwhFee DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_company_price PRIMARY KEY (companyPriceId)
);

CREATE TABLE electric_rate (
  electricRateId INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   timestamp VARCHAR(255),
   value DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_electric_rate PRIMARY KEY (electricRateId)
);

CREATE TABLE transaction (
  transactionId INTEGER NOT NULL,
   status INTEGER,
   companyFlatCharge DOUBLE PRECISION NOT NULL,
   companyRate DOUBLE PRECISION NOT NULL,
   isProcessed BOOLEAN NOT NULL,
   chargingStationId INTEGER,
   CONSTRAINT pk_transaction PRIMARY KEY (transactionId)
);

ALTER TABLE charging_station ADD CONSTRAINT uc_a085010f8def51cdf5612a321 UNIQUE (address, number);

ALTER TABLE charging_station ADD CONSTRAINT uc_charging_station_identifier UNIQUE (identifier);

ALTER TABLE charge ADD CONSTRAINT FK_CHARGE_ON_TRANSACTIONID FOREIGN KEY (transactionId) REFERENCES transaction (transactionId);

ALTER TABLE transaction ADD CONSTRAINT FK_TRANSACTION_ON_CHARGINGSTATIONID FOREIGN KEY (chargingStationId) REFERENCES charging_station (chargingStationId);